config/routes.rb
Rails.application.routes.draw do
  root 'post_images#top'
  get 'top' => 'post_images#top'
  get 'about' => 'post_images#about'
  get "search" => "users#search"
  get "users/:id/browsing_histories" => "users#browsing_histories"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :browsing_histories
  resources :post_images do
  resources :post_comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

resources :users do
	member do
		get :following, :followers
	end
end

resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

         has_many :post_images, dependent: :destroy
         has_many :post_comments, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :favorited_post_images, through: :favorites, source: :post_image
         has_many :browsing_histories, dependent: :destroy

         def already_favorited?(post_image)
          self.favorites.exists?(post_image_id: post_image.id)
        end

         attachment :profile_image

         has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
         has_many :followings, through: :following_relationships
         has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
         has_many :followers, through: :follower_relationships


  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def User.search(search, user_or_post, how_search)
        if user_or_post == "1"
            if how_search == "1"
                    User.where(['name LIKE ?', "%#{search}%"])
            elsif how_search == "2"
                    User.where(['name LIKE ?', "%#{search}"])
            elsif how_search == "3"
                    User.where(['name LIKE ?', "#{search}%"])
            elsif how_search == "4"
                    User.where(['name LIKE ?', "#{search}"])
            else
                    User.all
            end
         end
    end

    def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
 
    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
    end
 
    user
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])
    binding.pry

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def index
  	@user = current_user
  	@users = User.page(params[:id]).reverse_order
  	@post_image = PostImage.new
  	@post_images = PostImage.all
  end

  def show
  	@post_image = PostImage.new
  	@user = User.find(params[:id])
  	@post_images = @user.post_images.page(params[:page]).reverse_order
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to user_path(@user.id)
  	flash[:success] = 'success'
  	flash[:error] = 'error'
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def search
    @user_or_post = params[:option]
    @how_search = params[:choice]
    if @user_or_post == "1"
      @users = User.search(params[:search], @user_or_post, @how_search)
    else
      @post_images = PostImage.search(params[:search], @user_or_post, @how_search)
    end
  end

  def browsing_histories
    @user = User.find_by(id: params[:id])
    @browsing_histories = BrowsingHistory.where(user_id: @user.id)
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
     user == current_user
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_search.html.erb
<%= form_tag(search_path, :method => 'get') do %>
    <%= select_tag(:option, options_for_select([["ユーザー", "1"],["投稿","2"]]))%>
    <%= select_tag(:choice, options_for_select([["あいまい検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
    <%= text_field_tag :search %>
    <%= submit_tag 'Search' %>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div><%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/browsing_histories.html.erb
<section class="container wear-edit">
  <div class="row edit-row">
    <div class="col-md-8 col-sm-offset-2">
      <h2 class="edit-title">閲覧投稿一覧</h2>
			<% @browsing_histories.each do |browsing_histories| %>
  	<% post_image = PostImage.find_by(id: browsing_histories.post_image_id) %>
            <%= link_to post_image_path(post_image.id) do %>
              <%= attachment_image_tag post_image, :image, class: "book-img float-left", size: "300x300" %>
              <p class="float-left"><%= post_image.book_name %></p>
              <% end %>
          <% end %>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
	<h2>
		<%= @user.errors.count %>
		errors prohibited this obj from being saved
	</h2>
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
        <% end %>
    </ul>
 <% end %>

 <section class="col-md-8 col-sm-offset-2">
 	<h2>User Edit</h2>
 	<%= form_for(@user) do |f| %>
 	<h4 class="title">Name
 		<%= f.text_field :name %></h4>
 		<div class="form-group has-icon">
 			<div class="user-edit-image">
 			<h4 class="profile">Image</h4>
 			<%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg" %>
 			</div>
 			<%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
 			<h4 class="title">Introduction</h4>
 			<%= f.text_field :introduction %>
 			<br>
 			<div class="submit">
 				<%= f.submit 'Update User' %>
 			</div>
 			<% end %>
 		</div>
 	</section>
 </div>

app/views/users/index.html.erb
<div class="flash">
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

<section class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User Info</h2>
			<div class="user-image">
				<%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "60x60" %>
			</div>
			<table class="table table-striped">
				<tbody>
					<tr>
						<th>name</th>
						<th><%= @user.name %></th>
					</tr>
					<tr>
						<th>introduction</th>
						<th><%= @user.introduction %></th>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<p><%= link_to "", edit_user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
				</p>
			</div>

			<h2>New book</h2>
			<%= form_for (@post_image) do |f| %>
			<h4>Book  title</h4>
			<%= f.text_field :book_name, placeholder:"Book title" %>
			<h4>Book image</h4>
			<%= f.attachment_field :image %>
			<h4>Opinion</h4>
			<%= f.text_field :opinion, placeholder:"comment" %>
			<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
			<% end %>
		</div>

		<div class="col-xs-9">
         <h2>Users</h2>
         <table class="table table-striped">
         	<thead>
         		<tr>
         		<th class="th">profile image</th>
         		<th class="th">name</th>
         		<th class="th"></th>
         	    </tr>
            </thead>
            <tbody>
            	<% @users.each do |user| %>
            	<tr>
            		<td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "30x30" %>
            		</td>
            		<td><%= user.name %></td>
            		<td><%= link_to "Show", user_path(user.id) %></td>
            	</tr>
            	<% end %>
            </tbody>
        </table>
    </div>
</div>
</section>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/search.html.erb
<% if @user_or_post == "1"%>
    <h1>User</h1>
    <table>
        <% @users.each do |user| %>
        <thead>
            <tr>
                <th></th>
                <th><%= user.name %> </th>
            </tr>
        </thead>
        <% end %>
    </table>

<% elsif @user_or_post == "2" %>
    <h2>Books</h2>
            <div class="masonry-wrapper-cols">
                <div class="masonry-gutter"></div>
                <% @post_images.each do |post_image| %>
                 <div class="masonry-block">
                  <div class="block block-image v1">
                    <div class="block-image">
                        <div class="view view-first">
                            <%= link_to post_image_path(post_image.id) do %>
                            <%= attachment_image_tag post_image, :image, class: "book-img" %>
                            <% end %>
                        </div>
                    </div>
                    <div class="block-content">
                        <%= attachment_image_tag post_image.user, :profile_image, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
                        <h3 class="block-title">
                            <%= link_to post_image_path(post_image.id) do%>
                            <%= post_image.book_name %>
                            <% end %>
                        </h3>
                        <p><%= post_image.opinion %></p>
                        <ul class="inline-meta">
                        <li>By
                        <%= post_image.user.name %>
                        <%= link_to "#{post_image.post_comments.count}コメント", post_image_path(post_image.id), class: "comment-count" %>
                            <% if current_user.already_favorited?(post_image) %>
                            <%= link_to post_image_favorites_path(post_image), method: :delete do %>
                            <i class="fa fa-heart" aria-hidden="true" style="color: :red;"></i>
                            <%= post_image.favorites.count %>
                            いいね
                           <% end %>
                           <% else %>
                           <%= link_to post_image_favorites_path(post_image), method: :post do %>
                           <i class="fa fa-heart" aria-hidden="true" style="color: :red;"></i>
                           <%= post_image.favorites.count %>
                           いいね
                          <% end %>
                          <% end %>
                        </li>
                    </ul>
                  </div>
                </div>
            </div>
            <% end %>
        </div>
        </div>
        <% end %>

app/views/users/show.html.erb
<div class="flash">
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

<section class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User Info</h2>
			<div class="user-image">
				<%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "60x60" %>
			</div>
			<table class="table table-striped">
				<tbody>
					<tr>
						<th>name</th>
						<th><%= @user.name %></th>
					</tr>
					<tr>
						<th>introduction</th>
						<th><%= @user.introduction %></th>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<p><%= link_to "", edit_user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
				</p>
			</div>

			<h2>New book</h2>
			<%= form_for (@post_image) do |f| %>
			<h4>Book  title</h4>
			<%= f.text_field :book_name, placeholder:"Book title" %>
			<h4>Book image</h4>
			<%= f.attachment_field :image %>
			<h4>Opinion</h4>
			<%= f.text_field :opinion, placeholder:"comment" %>
			<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
			<% end %>
		</div>

<div class="col-xs-9">
  <h2>My Page</h2>
  <div class="profile-container">
  	<h3 class="profile-name"><%= @user.name %></h3>
  	<%= attachment_image_tag @user, :profile_image, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
  	<% if @user.id == current_user.id %>
  	<p><%= link_to "edit profile", edit_user_path(@user), class:"pull-right" %></p>
  	<% end %>

    <%= render 'users/follow_form' %>
    <%= render 'users/stats' %>
  </div>

  <ul>
  <li class="mypage-nav-list-item">
            <%= link_to "履歴一覧", "/users/#{@user.id}/browsing_histories" %>
          </li>
        </ul>

  <div  class="masonry-wrapper-cols">
  	<% @post_images.each do |post_image| %>
  	<div class="masonry-block">
  		<div class="block block-image">
  			<div class="block-image">
  				<div class="view view-first">
  					<%= link_to post_image_path(post_image.id) do %>
  					<%= attachment_image_tag post_image, :image, class: "my-img" %>
  					<% end %>
  				</div>
  			</div>
  			<div class="block-content">
  				<%= attachment_image_tag post_image.user, :profile_image, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
  				<h3 class="block-title">
  					<%= link_to post_image_path(post_image.id) do %>
  					<i class="fa fa-map-marker"></i>
  					<%= post_image.book_name %>
  					<% end %>
  				</h3>
  				<p><%= post_image.opinion %></p>
  				<ul class="inline-meta">
  					<li>By
  						<%= post_image.user.name %>
  						<%= link_to "#{post_image.post_comments.count}コメント", post_image_path(post_image.id), class: "comment-count" %>
  					</li>
  				</ul>
  			</div>
  		</div>
  	</div>
  	<% end %>
  	<%= paginate @post_images, class: "paginate" %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
<table>
<tr>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
<table>
<tr>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>