config/routes.rb
Rails.application.routes.draw do
  root 'post_images#top'
  get 'top' => 'post_images#top'
  get 'about' => 'post_images#about'
  get "search" => "users#search"
  get "users/:id/browsing_histories" => "users#browsing_histories"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :browsing_histories
  resources :post_images do
  resources :post_comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

resources :users do
	member do
		get :following, :followers
	end
end

resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post_image.rb
class PostImage < ApplicationRecord

	belongs_to :user
	attachment :image
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
    has_many :favorited_users, through: :favorites, source: :user
    has_many :browsing_histories, dependent: :destroy


	def PostImage.search(search, user_or_post, how_search)
        if how_search == "1"
            PostImage.where(['book_name LIKE ?', "%#{search}%"])
        elsif how_search == "2"
            PostImage.where(['book_name LIKE ?', "%#{search}"])
        elsif how_search == "3"
            PostImage.where(['book_name LIKE ?', "#{search}%"])
        elsif how_search == "4"
            PostImage.where(['book_name LIKE ?', "#{search}"])
        else
            PostImage.all
        end
    end


end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def top
    flash[:success] = 'Signed out successfully'
  end

  def about
  end


  def new
    @postimage = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to post_images_path
    flash[:success] = 'Book was successfully updated.'
  end

  def index
    @post_image_new = PostImage.new
    @post_images = PostImage.page(params[:page]).reverse_order
    @user = current_user
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
    @user = User.find(@post_image.user_id)
    @post_images = PostImage.new
    new_history = @post_image.browsing_histories.new
    new_history.user_id = current_user.id

    # 同一記事の重複チェック・重複時は古い履歴を削除
    if current_user.browsing_histories.exists?(post_image_id: "#{params[:id]}")
      old_history = current_user.browsing_histories.find_by(post_image_id: "#{params[:id]}")
      old_history.destroy
    end

    new_history.save

    histories_stock_limit = 10
    histories = current_user.browsing_histories.all
    if histories.count > histories_stock_limit
      histories[0].destroy
    end

  end

  def edit
    @post_image = PostImage.find(params[:id])
  end

  def update
    post_image = PostImage.new
    @post_image = PostImage.find(params[:id])
    @post_image.user_id = current_user.id
    if @post_image.update(post_image_params)
      redirect_to post_image_path(@post_image)
    else
      render :index
    end
    flash[:success] = 'Book was successfully updated.'
  end

  def destroy
    post_image = PostImage.find(params[:id])
    post_image.destroy
    redirect_to post_images_path
  end


  private
  def post_image_params
    params.require(:post_image).permit(:book_name, :image, :opinion)
  end

end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/_list.html.erb
<div class="flash">
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

<section class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User Info</h2>
			<div class="user-image">
				<%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "60x60" %>
			</div>
			<table class="table table-striped">
				<tbody>
					<tr>
						<th>name</th>
						<th><%= @user.name %></th>
					</tr>
					<tr>
						<th>introduction</th>
						<th><%= @user.introduction %></th>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<p><%= link_to "", edit_user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
				</p>
			</div>

			<h2>New book</h2>
			<%= form_for (post_image) do |f| %>
			<h4>Book  title</h4>
			<%= f.text_field :book_name, placeholder:"Book title" %>
			<h4>Book image</h4>
			<%= f.attachment_field :image %>
			<h4>Opinion</h4>
			<%= f.text_field :opinion, placeholder:"comment" %>
			<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
			<% end %>
		</div>

app/views/post_images/about.html.erb
<h1>aboutページ</h1>

app/views/post_images/edit.html.erb
	<div class="container">
		<div class="row">
<div class="col-md-6 col-md-offset-3">
<h1>Editing Book</h1>
<%= form_for(@post_image) do |f| %>
<div class="field row">
<h4 class="title">Title</h4>
<%= f.text_field :book_name %>
</div>
<div class="field row">
<h4 class="title">Opinion</h4>
<%= f.text_field :opinion %>
</div>
<div class="action row">
<input type="submit" name="commit" value="Update Book" class="btn btn-primary col-xs-12" data-disable-with="Update Book">
</div>
<% end %>

<%= link_to "Show", post_image_path(@post_image) %>
|
<%= link_to "Back", post_images_path %>
</div>
</div>
</div>
</div>

app/views/post_images/history.html.erb
<section class="container">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<% @post_images.each do |post_image| %>
  	<div class="masonry-block">
  		<div class="block block-image">
  			<div class="block-image">
  				<div class="view view-first">
  					<%= link_to post_image_path(post_image.id) do %>
  					<%= attachment_image_tag post_image, :image, class: "my-img" %>
  					<% end %>
  				</div>
  			</div>
  			<div class="block-content">
  				<%= attachment_image_tag post_image.user, :profile_image, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
  				<h3 class="block-title">
  					<%= link_to post_image_path(post_image.id) do %>
  					<i class="fa fa-map-marker"></i>
  					<%= post_image.book_name %>
  					<% end %>
  				</h3>
  				<p><%= post_image.opinion %></p>
  			</div>
  		</div>
  	</div>
  </div>
</div>
</section>

app/views/post_images/index.html.erb
<div class="flash">
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>


<section class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User Info</h2>
			<div class="user-image">
				<%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "60x60" %>
			</div>
			<table class="table table-striped">
				<tbody>
					<tr>
						<th>name</th>
						<th><%= @user.name %></th>
					</tr>
					<tr>
						<th>introduction</th>
						<th><%= @user.introduction %></th>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<p><%= link_to "", edit_user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
				</p>
			</div>

			<h2>New book</h2>
			<%= form_for (@post_image_new) do |f| %>
			<h4>Book  title</h4>
			<%= f.text_field :book_name, placeholder:"Book title" %>
			<h4>Book image</h4>
			<%= f.attachment_field :image %>
			<h4>Opinion</h4>
			<%= f.text_field :opinion, placeholder:"comment" %>
			<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
			<% end %>
		</div>

		<div class="col-xs-9">

			<h2>Books</h2>
			<div class="masonry-wrapper-cols">
				<div class="masonry-gutter"></div>
				<% @post_images.each do |post_image| %>
				 <div class="masonry-block">
				  <div class="block block-image v1">
				  	<div class="block-image">
				  		<div class="view view-first">
				  			<%= link_to post_image_path(post_image.id) do %>
				  			<%= attachment_image_tag post_image, :image, class: "book-img" %>
				  			<% end %>
				  		</div>
				  	</div>
				  	<div class="block-content">
				  		<%= attachment_image_tag post_image.user, :profile_image, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
				  		<h3 class="block-title">
				  			<%= link_to post_image_path(post_image.id) do%>
				  			<%= post_image.book_name %>
				  			<% end %>
				  		</h3>
				  		<p><%= post_image.opinion %></p>
				  		<ul class="inline-meta">
				  		<li>By
				  		<%= post_image.user.name %>
				  		<%= link_to "#{post_image.post_comments.count}コメント", post_image_path(post_image.id), class: "comment-count" %>
				  			<% if current_user.already_favorited?(post_image) %>
  				            <%= link_to post_image_favorites_path(post_image), method: :delete do %>
  				            <i class="fa fa-heart" aria-hidden="true" style="color: :red;"></i>
  				            <%= post_image.favorites.count %>
  				            いいね
  				           <% end %>
  				           <% else %>
  				           <%= link_to post_image_favorites_path(post_image), method: :post do %>
  				           <i class="fa fa-heart" aria-hidden="true" style="color: :red;"></i>
  				           <%= post_image.favorites.count %>
  				           いいね
  				          <% end %>
  				          <% end %>
				  		</li>
				  	</ul>
				  </div>
				</div>
			</div>
			<% end %>
			<%= paginate @post_images, class: "pagenate" %>
		</div>
	</div>
</div>
</section>
</div>
</div>

app/views/post_images/new.html.erb
<h1>PostImages#new</h1>
<p>Find me in app/views/post_images/new.html.erb</p>

app/views/post_images/show.html.erb
<%= render 'post_images/list', post_image: @post_images %>

<div class="col-xs-9 post_images_container">
  <h2>Book Detail</h2>
  <div class="post-item">
  	<div class="post-image">
  		<%= attachment_image_tag @post_image, :image, class:"post-comment-image" %>
  	</div>
  	<div class="post-content">
  		<%= attachment_image_tag @post_image.user, :profile_image,fallback: "no_image.jpg", size: "60x60", class:"profile-image" %>
  		<h2 class="post-title">
  			<%= @post_image.book_name %>
  		</h2>
  		<ul class="meta-info-cells v4 float-wrapper clearfix">
  			<li>
  				<i class="fa fa-user"></i>
  				By<%= link_to user_path(@user) do %>
  				<%= @post_image.user.name %>
  				<% end %>
  				<i class="fa fa-calender"></i>
  				<%= @post_image.created_at.strftime('%Y/%m/%d') %>
  				<% if current_user.already_favorited?(@post_image) %>
  				<%= link_to post_image_favorites_path(@post_image), method: :delete do %>
  				<i class="fa fa-heart" aria-hidden="true" style="color: :red;"></i>
  				<%= @post_image.favorites.count %>
  				いいね
  				<% end %>
  				<% else %>
  				<%= link_to post_image_favorites_path(@post_image), method: :post do %>
  				<i class="fa fa-heart" aria-hidden="true" style="color: :red;"></i>
  				<%= @post_image.favorites.count %>
  				いいね
  				<% end %>
  				<% end %>
  				<i class="fa fa-comment"></i>
  				<%= @post_image.post_comments.count %>
  				<% if @post_image.user == current_user %>
  				<%= link_to "edit", edit_post_image_path(@post_image) %>
  				<%= link_to "delete", post_image_path(@post_image), method: :delete %>
  				<% end %>
  			</li>
  		</ul>

      <div id="post_image_favorite">
             <%= render 'favorites/favorite', post_image: @post_image %>
          </div>

  		<div class="post-content-innner mt-20">
  			<p><%= @post_image.opinion %></p>
  		</div>
  	</div>
  	<hr>
  	<div class="comment-list bt style-2" id="comments">
  		<div class="float-wrapper">
  			<h2 class="comment-count">
  				<%= @post_image.post_comments.count %>
  				件コメント
  			</h2>
  		</div>
  		<ol>
  			<% @post_image.post_comments.each do |post_comment| %>
  			<li class="comment">
  				<div class="comment-body bb">
  					<div class="comment-avatar">
  						<%= attachment_image_tag post_comment.user, :profile_image, fallback: "no_image.jpg", class:"post-comment-image" %>
  					<div class="comment-text">
  						<div class="comment-author clearfix">
  						<%= link_to user_path(post_comment.user.id) do %>
  				        <%= post_comment.user.name %>
  				        <% end %>
  				        <span class="comment-mata">
  				        	<span class="comment-date">
  				        		<%= @post_image.created_at.strftime('%Y/%m/%d') %>
  				        	</span>
  				        </span>
  				    </div>
  				    <div class="comment-entry">
  				    	<%= post_comment.comment %>
  				    </div>
              
  				</div>
  			</div>
  		</li>
  		<% end %>
  	</ol>
  </div>
  <hr>
  <div class="section-title-wrapper style-1 v1 mt-30" id="divAddComment">
  	<h3 class="section-title left">
  		<span>Comment</span>
  	</h3>
  </div>
  <%= form_for [@post_image, @post_comment] do |f| %>
  <div class="row">
  	<div class="col-sm-12">
  		<%= f.text_field :comment, class: "form-control", placeholder: "コメントをここに" %>
  	</div>
  </div>
  <%= f.submit "submit", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
  <% end %>
</div>
</div>

app/views/post_images/top.html.erb
<div class="col-md-6 col-md-offset-2">
<ul class="slick-box"> <!--classは任意の名前でOK-->
  <li><%= image_tag('img/asia.jpg', class: 'block-image') %></li>
  <li><%= image_tag('img/italy.jpg', class: 'block-image') %></li>
  <li><%= image_tag('img/sunset.jpg', class: 'block-image') %></li>
  <li><%= image_tag('img/desert.jpg', class: 'block-image') %></li>
</ul>
</div>